### ISSUE TITLE
Thank you so much for your kind article/Budget Sourcing

### ISSUE THREAD

**Issue by flowerm1385** [Sjamilla/recruitmentexample#3]
I am trying make it private :)

**Comment by flowerm1385** [comment]
I am trying to make it private mode :)

**Comment by Sjamilla** [comment]
@flowerm1385 did this work? Let me know if you need any help with it!

**Comment by flowerm1385** [comment]
@Sjamilla thank you. Yes, your instruction given is clear and it works well. Have a nice day. :)

**Comment by Sjamilla** [comment]
Cool! Great to hear :)
